### PR TITLE
Fix macos build + CI for macos

### PR DESCRIPTION
**Pull request by adrienluitot**
Fixed issues for apple targets.
Fixed CI for apple targets

### CODE REVIEW

**Comment by Kreijstal** [comment]
Great job, we can compile openvaf on mac os now!

**Comment by Kreijstal** [comment]
Now for linux arm64 maybe we can do it over qemu from mac os arm64? but im not an expert on that

**Comment by adrienluitot** [comment]
> Now for linux arm64 maybe we can do it over qemu from mac os arm64? but im not an expert on that

Hmm... If the goal is to use qemu, it will work as well or even better on linux rather than macos?
According to github/roadmap#970 Arm64 with GitHub runner should arrive anytime soon. I don't know if it's better to wait for it or to use qemu?

**Comment by Kreijstal** [comment]
> > Now for linux arm64 maybe we can do it over qemu from mac os arm64? but im not an expert on that
> 
> Hmm... If the goal is to use qemu, it will work as well or even better on linux rather than macos? According to [github/roadmap#970](https://github.com/github/roadmap/issues/970) Arm64 with GitHub runner should arrive anytime soon. I don't know if it's better to wait for it or to use qemu?

you are right, its better to just wait, the problem is linux has to do x86 to arm translation which would be very expensive, more than just using hypervisor tools on mac os. However if native arm64 is coming that is even better.

**Comment by adrienluitot** [comment]
> you are right, its better to just wait, the problem is linux has to do x86 to arm translation which would be very expensive, more than just using hypervisor tools on mac os. However if native arm64 is coming that is even better.

I achieved to implement a CI Test on ubuntu 22 arm64 test with CircleCI, you can check my last (dirty) commits on my ci branch.
It was mainly for testing purposes, but if you want I can invite you to the organisation I made on CircleCI.

**Comment by Kreijstal** [comment]
That's amazing, so it works indeed on arm64... 
I think it is okay, I've learned a lot with this, I submitted a  PR to https://github.com/arpadbuermen/OpenVAF but he wants to really make sure llvm18 isn't buggier than llvm15

**Comment by adrienluitot** [comment]
Yes it sure does, even on my raspberry pi :)
I think it's not buggier, maybe it's even better, because there was issues related to things not from LLVM18, like the default arch.
And I don't know how much the rust tests cover, but they pass on every platform :D

**Pull request merged**
